apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-payment
  labels:
    app: pay

spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
      tier: web
  template:
    metadata:
      labels:
        app: payment
        tier: web
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
