apiVersion: v1
kind: Service
metadata:
   name: services-payment
   labels:
      app: service
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 80

    - name: tomcat
      port: 8080
      targetPort: 8080

  type: NodePort
  selector:
       app: payment
       tier: web
